COMMANDS = ["UPLOAD_FILE", "BLUP", "DOWNLOAD_FILE",
            "DELETE_FILE", "DELETE_DIR", "MAKE_DIR",
            "NEW_USER", "LOG_IN", "MOVE_FILE", "MOVE_DIR",
            "ASK_SHARE", "SHARE"]
PERMISSION_DENIED = "permission denied"
MAKE_DIR = "MAKE_DIR"
MOVE_DIR = "MOVE_DIR"
RE_UPLOAD_FILE = "RE_UPLOAD_FILE"
NEW_USER = "NEW_USER"
MOVE_FILE = "MOVE_FILE"
LOG_IN = "LOG_IN"
SOMETHING_WENT_WRONG = "something went wrong"
NO_USER = "NO_USER"
INCORRECT_PASSWORD = "password incorrect"
THREE_PARAMETER = 3
SHORT_SLEEP = 1
ERROR_FORMAT = "error"
FINE = "logged in"
WAIT = "WAIT"
SEPERATOR = " $$$ "
STARTER = 1
GUI_INIT = -1
GUI_TITLE = "Tomer Cloud Inc."
QUIT_BOTTON = "Quit"
MENU = "Menu"
SIGN_IN_PANEL_SIZE = (270, 225)
SELECT_DIRECTORY = "Folder Selection"
CHOOSE_YOUR_CLOUD_STATIC = "Choose Your Cloud"
NO_PASSWORD = ""
PYTHON = "python"
BLANK = ""
BROWSE_BTN = "Browse..."
SUBMIT_BTN = "Submit"
LONG_SLEEP = 3
SYSTEM_REGISTER_PANEL_SIZE = (250, 225)
INIT_CLOUD_GUI_SIZE = (300, 200)
USERNAME_STATIC = "Username"
PASSWORD_STATIC = "Password"
REGISTER_TITLE = "Register"
HOME_PAGE_TITLE = "Home"
SHARE_BTN = "Share"
SHARE_TITLE = "Share"
CHOOSE_FILE_TO_SHARE = "Choose A File To Share"
NEXT_BTN = "Next..."
ASK_FOR_SHARE_BTN = "Ask For Share"
SIGN_UP_BTN = "Sign Up"
SELECT = r"Select - Sign Up \ Log In"
LOG_IN_BTN = "Log In"
USERNAME_EXISTS = "username exists already"
START = 0
DIR_ADDED = "directory created successfully"
NO_DIR_ADDED = "no dir added"
DELETE_FILE = "DELETE_FILE"
DELETE_DIR = "DELETE_DIR"
CLIENT_REG = r"SOFTWARE\WOW6432Node\Cloud Server\Client"
SERVER_REG = r"SOFTWARE\WOW6432Node\Cloud Server"
OBSERVER = "observer"
ALLOW_OBS = "Allow"
DENY_OBS = "Deny"
ALLOW_BLUP = "Allow"
DENY_BLUP = "Deny"
PATH_CREATED = "path created!"
CONTINUE = "CONTINUE"
INFO_FILE = "info.txt"
LOGIN = "LOGIN"
APP_MODE = '0'
CLIENT_MODE = '1'
SIGNUP = "SIGNUP"
APPINFO = "\\AppInfo"
NO_CLOUD = ""
DOT = '.'
NO_COMMAND = "BLUP"
YAY = "YAY"
FILE_ALREADY_IN_CLOUD = "file in cloud"
END = -1
MSG_LEN = 1024
BYTE_NUMBER = 1024
IP_COMMAND = "IP"
CLIENT_CLOUD_COMMAND = "CLIENT_CLOUD"
USERNAME_COMMAND = "USERNAME"
NO_ENTERS = 0
PORT_COMMAND = "PORT"
FILE_DOESNT_EXIST = "file doesn't exist"
FILE_END = b'NO_MORE'
FILE_SENT = 'file uploaded successfully !!!'
MSG_FILL = 4
NO_PARAMETERS = 0
ONE_PARAMETER = 1
TWO_PARAMETER = 2
THREE_PARAMETERS = 3
PROPORTION = 0
BORDER_LARGE = 15
BORDER_SMALL = 7
BYTE = 4
USERNAME_REG = "username"
PASSWORD_REG = "password"
CLOUD_REG = "CLIENT_CLOUD"
PRM = 1
PORT = 6969
USER_ADDED = "new username added"
NOT_ADDED = "username already exists"
SERVER_FELL = str(1)
CLOUD_FORMAT = 'cloud'
ADDER = 1
TEMPORARY_FILES = r"E:\12\Project\Temp"
UPLOAD_FILE = "UPLOAD_FILE"
DOWNLOAD_FILE = "DOWNLOAD_FILE"
NOT_IN_CLOUD = "file doesn't exist in cloud"
READY = "ready"
QUIT_BTN = 'Quit'
QUIT_APP = 'Quit Application'
MENU_GUI = 'Menu&'
NONE_VALID = "you entered a non valid value"
DB_COMMAND_USERS = "select * from users"
DB_COMMAND_USERNAME = "select username from users"
OK = "ok"
BYE = "bye"
START_COUNT = 1
SECOND = 1
FILE_DOWNLOADED = 'file is opening right now...'
IP_REG = "IP"
PORT_REG = "port"
REG_CONST = 0
